import { useCallback, useEffect, useState } from "react";
import { MessageSquarePlus, Send } from "lucide-react";
import useWorkspaceContext from "../../hooks/useWorkspaceContext";
import { createConversation, getConversation, listConversations, sendWorkspaceMessage } from "../../services/api";

export default function ConversationsView() {
  const { activeWorkspaceId } = useWorkspaceContext();
  const [conversations, setConversations] = useState([]); const [active, setActive] = useState(null); const [text, setText] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const select = useCallback(async (conversation) => { setActive(await getConversation(activeWorkspaceId, conversation.id)); }, [activeWorkspaceId]);
  const refresh = useCallback(async () => { if (!activeWorkspaceId) return; const values = await listConversations(activeWorkspaceId); setConversations(values); if (values[0]) setActive((current) => current?.id ? current : null); }, [activeWorkspaceId]);
  useEffect(() => { setActive(null); refresh().catch((err) => setError(err.message)); }, [activeWorkspaceId, refresh]);
  async function addConversation() { const created = await createConversation(activeWorkspaceId); setConversations((items) => [created, ...items]); await select(created); }
  async function submit(event) { event.preventDefault(); if (!text.trim() || !active || loading) return; const content = text.trim(); setText(""); setLoading(true); setError(""); setActive((current) => ({ ...current, messages: [...current.messages, { id: `pending-${Date.now()}`, role: "user", content, citations: [] }] })); try { const reply = await sendWorkspaceMessage(activeWorkspaceId, active.id, content); setActive((current) => ({ ...current, messages: [...current.messages, reply] })); refresh(); } catch (err) { setError(err.message); setActive((current) => ({ ...current, messages: current.messages.filter((message) => message.id !== undefined && !message.id.startsWith("pending-")) })); } finally { setLoading(false); } }
  return <section className="conversation-layout"><aside className="conversation-list"><div><h2>Conversations</h2><button onClick={addConversation} aria-label="Nouvelle conversation"><MessageSquarePlus size={18} /></button></div>{conversations.length === 0 ? <p>Créez une première conversation.</p> : conversations.map((conversation) => <button key={conversation.id} className={active?.id === conversation.id ? "active" : ""} aria-pressed={active?.id === conversation.id} onClick={() => select(conversation)}>{conversation.title}</button>)}</aside><section className="conversation-panel">{active ? <><header><span>CONVERSATION ACTIVE</span><h2>{active.title}</h2></header><div className="message-list">{active.messages.length === 0 && <p className="empty-state">Posez votre première question à Nova.</p>}{active.messages.map((message) => <article key={message.id} className={`workspace-message ${message.role}`}><span>{message.role === "user" ? "Vous" : "NOVA"}</span><p>{message.content}</p>{message.citations?.length > 0 && <div className="citations">{message.citations.map((citation, index) => <small key={`${citation.document_id}-${index}`}>Source · {citation.document_name}</small>)}</div>}</article>)}{loading && <article className="workspace-message assistant"><span>NOVA</span><p>Analyse du Workspace…</p></article>}</div>{error && <p className="inline-error" role="alert">{error}</p>}<form className="message-composer" onSubmit={submit}><input aria-label="Message à Nova" value={text} onChange={(event) => setText(event.target.value)} placeholder="Interrogez ce Workspace…" disabled={loading} /><button type="submit" aria-label="Envoyer le message" disabled={loading || !text.trim()}><Send size={18} /></button></form></> : <div className="empty-state"><h2>Vos conversations</h2><p>Créez une conversation pour commencer à travailler avec ce Workspace.</p><button onClick={addConversation}>Nouvelle conversation</button></div>}</section></section>;
}
